import { Toaster } from "@/components/ui/toaster";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider
        appearance={{
          // layout: {
          //   logoImageUrl: "#TODO Placehollder For APP Logo Icon (muchat)",
          //   socialButtonsVariant: "iconButton",
          // },
          variables: {
            colorText: "#fff",
            colorPrimary: "#3b82f6",
            colorBackground: "#111827",
            colorInputText: "#fff",
          },
        }}
      >
        <body className={`${inter.className} bg-gray-950`}>
          {children}
          <Toaster />
        </body>
      </ClerkProvider>
    </html>
  );
}
